server:
  port: 9090

spring:
  application:
    name: resource-server

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/oauth2/jwks

keySetURI: http://localhost:8080/oauth2/jwks