server:
  port: 8080

spring:
  application:
    name: authorization-server

#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem
#    username: sa
#    password:

#  jpa:
##    hibernate:
##      #      ddl-auto: update
##      ddl-auto: create
##    defer-datasource-initialization: true
#
#    properties:
#      hibernate:
#        # show_sql: true          # SQL 출력
#        format_sql: true        # SQL 포맷팅
#        use_sql_comments: true  # SQL에 주석 추가
#        default_batch_fetch_size: 1000  # 성능 최적화
#        # dialect: org.hibernate.dialect.H2Dialect  # MySQL에 맞는 방언 설정
#        globally_quoted_identifiers: true # SQL문이 실행될 때 백틱(`)로 테이블과 컬럼을 자동으로 감쌈
#        jpa:
#          hibernate:
#            ddl-auto: create
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true

#`  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}`